markdown: kramdown
theme: jekyll-theme-cayman

title: Voedselprijzen in relatie tot migratiestromen, neerslag en temperatuur
decription: M.F.Amersfoort (11857412), A.Labro (11872470), B.L.Leijnse (11872888), P.T.Pos (11342536)
